CREATE SEQUENCE  "USER_INFORMATION_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE "USER_INFORMATION" (
	"ID" NUMBER DEFAULT "USER_INFORMATION_ID_SEQ".NEXTVAL NOT NULL,
	"USER_ID" NUMBER NOT NULL,
	"USER_TYPE" VARCHAR2(150 CHAR) NOT NULL,
	"DATA" CLOB NOT NULL,
	"DATE_CREATED" TIMESTAMP (6) NOT NULL,
	"DATE_UPDATED" TIMESTAMP (6),
	"VERSION" NUMBER NOT NULL,
	CONSTRAINT "USER_INFORMATION_PK" PRIMARY KEY ("ID"),
	CONSTRAINT "USER_INFORMATION_USERS_FK" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID")
	);
