CREATE SEQUENCE  "CAR_RIDES_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE "CAR_RIDES" (
	"ID" NUMBER DEFAULT "CAR_RIDES_ID_SEQ".NEXTVAL NOT NULL,
	"USER_ID" NUMBER NOT NULL,
	"AVAILABLE_SEATS" NUMBER NOT NULL,
	"MAXIMUM_SEATS" NUMBER NOT NULL,
	"TAKE_OFF_DATE" TIMESTAMP(6) NOT NULL,
	"CITY_FROM" VARCHAR2(64 CHAR) NOT NULL,
    "CITY_TO" VARCHAR2(64 CHAR) NOT NULL,
    "PRICE" NUMBER(5,2) NOT NULL,
	"DATE_CREATED" TIMESTAMP (6) NOT NULL,
	"DATE_UPDATED" TIMESTAMP (6),
	"VERSION" NUMBER NOT NULL,
	CONSTRAINT "USERS_PK" PRIMARY KEY ("ID"),
	CONSTRAINT "USER_INFORMATION_USERS_FK" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID")
	);
