CREATE SEQUENCE  "USERS_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE "USERS" (
	"ID" NUMBER DEFAULT "USERS_ID_SEQ".NEXTVAL NOT NULL,
	"NAME" VARCHAR2(150 CHAR) NOT NULL,
	"TELEPHONE_NUMBER" VARCHAR2(32 CHAR) NOT NULL UNIQUE,
	"EMAIL" VARCHAR2(150 CHAR) NOT NULL,
	"DATE_CREATED" TIMESTAMP (6) NOT NULL,
	"DATE_UPDATED" TIMESTAMP (6),
	"VERSION" NUMBER NOT NULL,
	CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
	);
